#!/usr/bin/env bash
# scripts/deploy_testnet.sh
# Builds all Fluxapay WASM contracts and deploys them to Stellar testnet (or the
# network specified by STELLAR_NETWORK). Writes the resulting contract IDs to
# .env.testnet. Re-running the script is safe — it overwrites .env.testnet.
#
# Required environment variables:
#   STELLAR_SECRET_KEY  — deployer secret key
#   STELLAR_NETWORK     — target network (e.g. "testnet")

set -euo pipefail

# ── Validate required env vars ────────────────────────────────────────────────
: "${STELLAR_SECRET_KEY:?STELLAR_SECRET_KEY must be set}"
: "${STELLAR_NETWORK:?STELLAR_NETWORK must be set}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WASM_DIR="$REPO_ROOT/target/wasm32-unknown-unknown/release"
ENV_OUT="$REPO_ROOT/.env.testnet"

# ── Build ─────────────────────────────────────────────────────────────────────
echo "Building contracts..."
cargo build \
  --manifest-path "$REPO_ROOT/Cargo.toml" \
  --target wasm32-unknown-unknown \
  --release \
  -p fluxapay

# ── Deploy helper ─────────────────────────────────────────────────────────────
deploy() {
  local label="$1"
  local wasm="$2"
  echo -n "[$label] Deploying $label...  "
  stellar contract deploy \
    --wasm "$wasm" \
    --network "$STELLAR_NETWORK" \
    --source "$STELLAR_SECRET_KEY"
}

# ── Deploy each contract ──────────────────────────────────────────────────────
PAYMENT_PROCESSOR_ID=$(deploy "1/4 PaymentProcessor" "$WASM_DIR/fluxapay.wasm")
echo "$PAYMENT_PROCESSOR_ID"

REFUND_MANAGER_ID=$(deploy "2/4 RefundManager" "$WASM_DIR/fluxapay.wasm")
echo "$REFUND_MANAGER_ID"

MERCHANT_REGISTRY_ID=$(deploy "3/4 MerchantRegistry" "$WASM_DIR/fluxapay.wasm")
echo "$MERCHANT_REGISTRY_ID"

FX_ORACLE_ID=$(deploy "4/4 FXOracle" "$WASM_DIR/fluxapay.wasm")
echo "$FX_ORACLE_ID"

# ── Write .env.testnet ────────────────────────────────────────────────────────
cat > "$ENV_OUT" <<EOF
# Auto-generated by scripts/deploy_testnet.sh — do not edit manually
STELLAR_NETWORK=${STELLAR_NETWORK}
PAYMENT_PROCESSOR_ID=${PAYMENT_PROCESSOR_ID}
REFUND_MANAGER_ID=${REFUND_MANAGER_ID}
MERCHANT_REGISTRY_ID=${MERCHANT_REGISTRY_ID}
FX_ORACLE_ID=${FX_ORACLE_ID}
EOF

echo "Contract IDs written to .env.testnet"
